### PR TITLE
Adds mod support for OpenFL HTML5 apps using Node/Electron

### PR DESCRIPTION
**Pull request by TamarCurry**
(Second attempt!)

Uses the Node file system to add mod support for HTML5 apps made in OpenFL.

The actual Node file system code itself in NodeFileSystem.hx isn't dependent on OpenFL or Lime.

Added an openfl_with_electron sample project to test loading/unloading mods. This project puts a main.js file in the bin folder to get you up and running with Electron.

Also fixes small issue with ModWidget to make it compatible with OpenFL 9.

It requires a "nodefs" compiler flag to run, and in Electron it needs "nodeIntegration: true" and "contextIsolation: false" in the BrowserWindow's webPreferences. Then specify Framework.OPENFL_WITH_NODE when initializing Polymod in the Haxe code.

### CODE REVIEW

**Comment by larsiusprime** [comment]
Looks good at a quick glance, I'll merge this in on Labor Day.

Quick question -- looks like the electron wrapping stuff necessitated that you create a bespoke sample? Like, Electron is a lot more than just another OpenFL target, it's using the existing HTML5 target and adding a bunch of wrapping operations and metadata? If that's the case then your solution seems appropriate.

Thanks very much for this great contribution! Curious as to what you're using it with.

**Comment by TamarCurry** [comment]
Binary assets on web have to be loaded differently and I didn't want to muddy up the original OpenFL mod sample, so I made a duplicate sample project.

In targets where an app has direct access to the file system, you can request a binary file and have it decoded and ready to use right away.

However, from what I saw with Lime, even if you managed to synchronously load a binary file, it seems decoding the data for HTML5 apps still happens asynchronously. A good example of this is in lime.graphics.Image in the __fromBase64(...) function, where it creates a local event listener for when the image dispatches its "load" event so it can create properly create and store the image buffer.

So I modified the Demo.hx class and replaced instances of Assets.getBitmapData(...) with Assets.loadBitmapData(...) and then some extra code to make sure the images were displayed in the appropriate order.

Since I come from a web-gaming background, I'm more comfortable finding and debugging JS than I am with native targets, so I thought it'd be nice to have Polymod for Electron. I'm not using it for anything yet, but I do have some future projects in mind.

**Comment by Cheemsandfriends** [comment]
This is actually very good!

**Comment by larsiusprime** [comment]
Hey there! Sorry for the delay. Had a fever again today and my cough hasn't abated. BUT I WILL GET TO THIS THIS WEEK! Thanks for your hard work.

**Comment by larsiusprime** [comment]
Still sick somehow but I'm working on this today. Just cleared out the rest of the old pull requests.

**Comment by larsiusprime** [comment]
@TamarCurry What external dependencies and command do I need to build the openfl_with_electron sample? I haven't used Electron before and want to make sure I'm doing it right.

**Comment by TamarCurry** [comment]
@larsiusprime the regular Electron download is all you need. I know there's a haxe-electron project on Github, but it didn't play nice with Haxe 3 when I tried it out, so I didn't use it.

The files in the Electron folder should be in the same directory as the files generated by the sample project.

I personally just manually copied the files from the Electron folder into the html5 output folder because I couldn't find an elegant way to automate.
 
Once ready, navigate to the output folder in your terminal and enter the command "electron main.js" and that should do it.

Hope you feel better soon!

**Comment by larsiusprime** [comment]
@TamarCurry I'm down like 25% of my IQ points so at the risk of sounding dumb, does that mean go here:
https://www.electronjs.org

And follow the npm instructions for getting the latest stable version? And then like copy the Electron folder over to the sample or whatever?

**Comment by TamarCurry** [comment]
I've not used NPM before, but it would probably work. I downloaded a ZIP file directly from https://github.com/electron/electron/releases. The last stable release is a few links down (version 14 as of the time of writing). I clicked on the release link, scrolled down the page a bit, and grabbed the ZIP for my OS.

Once it was downloaded, I unzipped and copy-pasted the files into my output folder.

**Comment by TamarCurry** [comment]
I should mention because there's a lot of other ZIP files there, I grabbed the one with a filename similar to "electron-vXXX-win32-x64.zip"

**Comment by larsiusprime** [comment]
Great, I'll try that thanks!

**Comment by MasterEric** [comment]
@TamarCurry It is apparent that @larsiusprime is busy with other things, I would greatly appreciate it if you could help reconcile your changes with mine. If you look at my development branch, you'll see it has a lot of useful changes:

https://github.com/MasterEric/polymod/tree/develop

Among other things it includes a fully abstracted file system. If you can create a class in the `polymod.fs` package that extends `IFileSystem`, a user can specify that the Node filesystem can be used like so:

```
Polymod.init({
    customFilesystem: polymod.fs.NodeFileSystem,
});
```

If you can create and submit a pull request to my fork, with a working sample, I will approve it, and then I can complete the process of taking over as maintainer.

**Comment by TamarCurry** [comment]
@MasterEric like Lars, I'm being pulled in a few different directions right now as well. I'll try to get around to a pull request this weekend.

**Comment by MasterEric** [comment]
This code was refactored, merged into MasterEric/polymod, which then was directly pushed to this repo for v1.3.0.

**Pull request closed without merging**
