### PR TITLE
Add the option of custom append and merge files

### PR DESCRIPTION
**Pull request by Cheemsandfriends**
The option of appending and merging stuff is really cool but,
It's kinda strict and kinda bad that it's not customisable the folder.
This can add a new customisation to the stuff

### CODE REVIEW

**Comment by Cheemsandfriends** [comment]
Idk how to add more than one commit on more than a file srry

**Comment by Cheemsandfriends** [comment]
But basically it's just replacing the "_append" and "_merge" with Util.appendFile and Util.mergeFiles

**Comment by MasterEric** [comment]
Great idea! I will do that cleanup for you soon and merge it.

Thank you so much for contributing!

**Comment by Cheemsandfriends** [comment]
> Great idea! I will do that cleanup for you soon and merge it.
> 
> Thank you so much for contributing!

Yeah, Glad you liked the idea!
And maybe there should be a Polymod function like "setComplementaryFiles".
That would make like instead of the `_polymod_meta`, `_polymod_pack` and stuff
You could customise the way you want it. So instead of  `_polymod_meta` you could add your custom name like `metaFile`
or something like that lol

**Comment by Cheemsandfriends** [comment]
I discovered how to make more than One commit, I'll add new stuff

**Comment by Cheemsandfriends** [comment]
I think that the `some old version that worked I think` to `I think it could work... Maybe Idk` Is really optional and maybe it could break.
But the customisation of append files and Polymod can work

**Comment by MasterEric** [comment]
Hey, I'm going to rework how the logic for these config options works overall, but since I want to give you credit for contributing to the project, I'll merge your PR first before doing that.

Thank you very much for helping out! You will be credited in the changelogs for 1.3.1 and I greatly appreciate any further feedback or contributions you may bring to Polymod in the future.

**Comment by MasterEric** [comment]
@Cheemsandfriends Yeah, it looks like you undid a lot of the file system changes I made so this'll take some work.

**Comment by MasterEric** [comment]
Okay, I've completed a new system for setting configurable options.

To set the append folder for mods, you have two options:
1. Add a `<haxedef name="POLYMOD_APPEND_FOLDER" value="_append" />` to your `project.xml`.
2. Add `PolymodConfig.appendFolder = "_append";` to your code somewhere. Make sure it's before you call `Polymod.init` and before you load any assets.

The functions that were added to set all the values were removed since you can now just set the values directly.

The value defined in code override the values defined in your project XML, which override the defaults.

**Comment by Cheemsandfriends** [comment]
> Okay, I've completed a new system for setting configurable options.
> 
> To set the append folder for mods, you have two options:
> 
> 1. Add a `<haxedef name="POLYMOD_APPEND_FOLDER" value="_append" />` to your `project.xml`.
> 2. Add `PolymodConfig.appendFolder = "_append";` to your code somewhere. Make sure it's before you call `Polymod.init` and before you load any assets.
> 
> The functions that were added to set all the values were removed since you can now just set the values directly.
> 
> The value defined in code override the values defined in your project XML, which override the defaults.

Sounds good!
Sorry for undoning all the stuff, I basically was copying my Polymod version. (Which is an old one but with the removed deprications and stuff)
At least I helped the project on something lol

**Pull request merged**
