### PR TITLE
Remove openfl deps

### PR DESCRIPTION
**Pull request by larsiusprime**

### CODE REVIEW

**Comment by larsiusprime** [comment]
Merging these changes into a branch for now so I can work on a refactor

**Comment by sh-dave** [comment]
Got a first test version with substituted image assets running in Kha running now.

image

**Comment by larsiusprime** [comment]
Cool, I've been making good progress on my HEAPS demos. Let me know when you've got something so I can coordinate what I'm doing with your changes.

**Comment by sh-dave** [comment]
Oki, i'll watch your changes to the genericbackends branch, will merge into my fork and contribute to the KhaBackend then.

**Comment by larsiusprime** [comment]
Cool, bit of a mess at the moment :) Not sure it even compiles.

**Pull request merged**
