### PR TITLE
Fix bad syntax in PolymodFileSystem.hx

### PR DESCRIPTION
**Pull request by byemc**

### CODE REVIEW

**Comment by byemc** [comment]
sorry, pressed enter accidentally, adding more details now...

**Comment by byemc** [comment]
Fixes the syntax error in `PolymodFileSystem.hx`

Solves issues #107 and #108, maybe more.

**Comment by byemc** [comment]
hiya, just checking in, 

what's the progress on this PR? it reverses a pretty breaking change that stops the library working (for FNF modding anyway)

^bye

**Comment by TON-Games** [comment]
DEV PLZ FIX DA PROBLEM

**Comment by MasterEric** [comment]
Sorry I've been so busy, just posted a 1.5.3 with some minor fixes I've been working on, including a proper one for this issue.

**Comment by byemc** [comment]
I was looking thru your changes and it doesnt look like it's fixed. I'm at school rn so I'll elaborate further

**Comment by MasterEric** [comment]
I just looked through the changes your PR makes and they're ridiculous. You are comparing whether the variable IS the class, rather than whether they are an instance of the class.

**Comment by byemc** [comment]
I was just saying, after made those *exact* changes it fixed my problem (not being able to compile Friday Night Funkin') immediatley. I don't actually know Haxe, I thought if I sent a PR with the changes that worked for me it could be useful to others. I just tested it now with a GitHub codespace for `ninjamuffin99/Funkin` and it's working fine. Thanks for fixing it!

**Pull request closed without merging**
