### PR TITLE
i think i fixed the path for the keys

### PR DESCRIPTION
**Pull request by beeanie**
i think i fixed the path for the keys

### CODE REVIEW

**Comment by approachcircle** [comment]
i'll apply those changes locally on my installation of polymod to test them, and i'll post the results after

**Comment by approachcircle** [comment]
after applying the changes, it seems like it just broke things even more, these errors now get displayed:
`C:/HaxeToolkit/haxe/lib/polymod/1,4,2/polymod/backends/OpenFLBackend.hx:20: characters 39-52 : Class<openfl.utils.AssetCache> has no field getBitmapKeys`
`C:/HaxeToolkit/haxe/lib/polymod/1,4,2/polymod/backends/OpenFLBackend.hx:20: characters 15-54 : You can't iterate on a Dynamic value, please specify Iterator or Iterable`
`C:/HaxeToolkit/haxe/lib/polymod/1,4,2/polymod/backends/OpenFLBackend.hx:22: characters 28-44 : Class<openfl.utils.AssetCache> has no field removeBitmapData`
`C:/HaxeToolkit/haxe/lib/polymod/1,4,2/polymod/backends/OpenFLBackend.hx:24: characters 39-50 : Class<openfl.utils.AssetCache> has no field getFontKeys`
`C:/HaxeToolkit/haxe/lib/polymod/1,4,2/polymod/backends/OpenFLBackend.hx:24: characters 15-52 : You can't iterate on a Dynamic value, please specify Iterator or Iterable`
`C:/HaxeToolkit/haxe/lib/polymod/1,4,2/polymod/backends/OpenFLBackend.hx:26: characters 28-38 : Class<openfl.utils.AssetCache> has no field removeFont`
`C:/HaxeToolkit/haxe/lib/polymod/1,4,2/polymod/backends/OpenFLBackend.hx:28: characters 39-51 : Class<openfl.utils.AssetCache> has no field getSoundKeys`
`C:/HaxeToolkit/haxe/lib/polymod/1,4,2/polymod/backends/OpenFLBackend.hx:28: characters 15-53 : You can't iterate on a Dynamic value, please specify Iterator or Iterable`
`C:/HaxeToolkit/haxe/lib/polymod/1,4,2/polymod/backends/OpenFLBackend.hx:30: characters 28-39 : Class<openfl.utils.AssetCache> has no field removeSound`

**Comment by beeanie** [comment]
ohhh use this openfl

**Comment by beeanie** [comment]
https://github.com/MasterEric/openfl

**Comment by beeanie** [comment]
ima just wait for master eric to fix it

**Comment by approachcircle** [comment]
will it fix the issue where polymod can't see the methods that you added in your fork of openfl that i talked about [here](https://github.com/larsiusprime/polymod/pull/100#issuecomment-1044849618)? and if not, what is the fix actually gonna be?

**Comment by approachcircle** [comment]
@MasterEric i actually just fixed all of the issues, and now fnf compiles which is what i've been trying to do from the beginning, and the fixes i've made don't require you to change your fork of openfl at all, so i'll open a pull request to merge all of the fixes

**Pull request closed without merging**
